# Generated by Django 6.0 on 2025-12-31 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='BRAND.', max_length=100)),
                ('about_text', models.TextField(default='Defining modern luxury through meticulous craftsmanship and ethical sourcing.')),
                ('footer_address', models.CharField(default='123 Luxury Ave, DHAKA', max_length=255)),
                ('footer_phone', models.CharField(default='+880 123 456 789', max_length=50)),
                ('footer_email', models.EmailField(default='contact@brand.com', max_length=254)),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
