# Generated by Django 6.0 on 2026-01-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_colors_product_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='return_window_days',
            field=models.PositiveIntegerField(default=14, help_text='Number of days after delivery that a return can be requested.'),
        ),
    ]
